spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{0}: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{0}: %msg%n"